### PR TITLE
Mark edits as minor, per some users' request

### PR DESCRIPTION
**Pull request by nemobis**
Two users requested the flag:
https://en.wikipedia.org/?diff=837495483
https://en.wikipedia.org/?diff=841824562

It's not an unanimous request, though.

### CODE REVIEW

**Comment by jorlowitz** [comment]
I think marking these edits as minor as they are also being contested by
some is not a good idea.  I'd decline this one.

**Comment by nemobis** [comment]
Jake Orlowitz, 07/11/2018 01:23:
> I think marking these edits as minor as they are also being contested by
> some is not a good idea. I'd decline this one.

As I previously expressed I also prefer to be cautious and not mark as 
minor, but I don't want to outright dismiss such a request either. I'll 
wait a few days and then close this pull request if nobody supports it.

**Comment by wetneb** [comment]
If this is contentious then it should not be too hard to add a checkbox to let the user decide?

**Comment by nemobis** [comment]
Antonin Delpeuch, 07/11/2018 11:31:
> If this is contentious then it should not be too hard to add a checkbox 
> to let the user decide?

MediaWiki already offers such a preference (which applies to all edits 
by default), but the English Wikipedia has disabled it. I'd rather avoid 
cluttering the interface for this, especially considering that no other 
wiki would need it.

**Pull request closed without merging**
