### PR TITLE
New project structure

### PR DESCRIPTION
**Pull request by CristianCantoro**
This commit addresses [T179368][T179368] in Phabricator. This is a work in progress towards building a new testing infrastructure for the project. It would be nice if we could do it in a piecemeal fashion so that we don't break anything in while adding what we need.

[T179368]: https://phabricator.wikimedia.org/T179368

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks @CristianCantoro! I welcome a new structure, however I'm not sure why it's useful to put everything in a `src/oabot` folder? I think it would make sense to put all the python files in a proper python module, but wouldn't it be simpler if we keep the rest (templates, static files) outside of that? But if you know of any established good practices I'm more than happy to follow them.

**Comment by CristianCantoro** [comment]
HI @wetneb, this [post](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) argues the merits of having a `src` folder. 
On the other hand the [recommended structure](http://flask.pocoo.org/docs/0.12/tutorial/testing/) packages everything in its own module including static files and templates (see also, the [reference example `flaskr` application](https://github.com/pallets/flask/tree/master/examples/flaskr)). See also [here](http://exploreflask.com/en/latest/organizing.html).

For this reason, I am going with the idea of having a module and also a `src` folder. I am of course open to changes, but the idea is that having a structure that people would recognize would simplify contributing to the project.

Feel free to take your time and evaluate alternatives and/or the organization that works best in your opinion.

**Comment by wetneb** [comment]
@CristianCantoro sure, let's do that then! thanks for the links.

**Comment by Samwalton9** [comment]
Is there a possibility that this would break on Toolforge?

Toolforge default configs apparently expect app.py to be located at src/app.py (https://wikitech.wikimedia.org/wiki/Help:Toolforge/My_first_Flask_OAuth_tool) - here it would be in src/oabot/app.py

**Comment by wetneb** [comment]
@Samwalton9 good catch! Currently I have cloned the repo in `www/python/src`… We can move `app.py` to `src/app.py` in the repo, and I'll just to move the local copy up a directory on tools labs.

**Comment by CristianCantoro** [comment]
@Samwalton9, @wetneb good catch, I will update the pull request. Please *do check* if everything still works.

**Comment by CristianCantoro** [comment]
The new commit reorganizes the project as follows:
```
oabot
└─ src
   └─ oabot
   │  ├─ __init__.py
   │  ├─ ...
   │  ├─ static
   │  │ ├─  css
   │  │ ├─  js
   │  │ ├─ ...
   │  │ └─ favicon.ico
   │  ├─ templates
   │  │ ├─ ...
   │  │ └─ index.html
   │  └─ config
   │     ├─ config.in (not in the repo, ignored)
   │     └─ config.sample.in
   ├─ app.py
   └─ zotero_cache_key.txt (not in the repo, ignored)
```
Some changes to note:
* the urls for serving static css and js files are now `<root>/static/css` and `<root>/static/js` instead of `<root>/css` and `<root>/js`
* the configuration file is now in the subdirectory `config`

**Pull request merged**
