### PR TITLE
Reject button

### PR DESCRIPTION
**Pull request by VorontsovIE**

### CODE REVIEW

**Comment by wetneb** [comment]
@VorontsovIE I've deployed your code, @jorlowitz @Samwalton9  let me know if you're happy with the results and then we can merge.

**Comment by VorontsovIE** [comment]
I didn't recognized that there are two similar pages - to review multiple edits or only one edit. I've done work for multi-change page only yet. Will fix simgle-edit page soon as well

**Comment by VorontsovIE** [comment]
Please take a look now. I've added reject button on a single-edit page too.
I'm sorry for a mess in commits. I'd have been working in a separate branch not in master

**Comment by wetneb** [comment]
@VorontsovIE Thanks a lot! I have deployed your fork on wmflabs.

**Comment by Samwalton9** [comment]
Looked through the code but couldn't immediately tell - could you briefly explain how the Reject button works? If I reject a proposed edit, does no one else see that proposed edit? Or is it just me who doesn't see it going forward?

**Comment by VorontsovIE** [comment]
@Samwalton9 Sure! Suggestions (which are stored in file cache) have a status field. Reject button just sets status of selected fields to `rejected`. Suggestions with rejected status are filtered out when one tries to load a random suggestion or a list of all suggestions for a certain page. So nobody sees them again (while page cache is not be reloaded). When reject is clicked on multi-suggestions page, it redirects to the same page if some edits still exists after rejection, and redirects to a random edit when no more suggestions that are not rejected are on page.
This feature introduces one bug which needs to be resolved yet: https://phabricator.wikimedia.org/T180672
Also I'm not sure that list of check-buttons which can be either all submitted or all rejected at once - is a good solution, it's a bit counterintuitive. Though, I think that feature with bad UX and sometimes showing no random suggestions (when some suggestion exist) is still better than no rejection button at all.
Hope to fix a problem described in a phabricator bug soon. Would be grateful for input on better UX. May be we need confirmation before rejecting several edits at once or some other solution.

**Comment by Samwalton9** [comment]
Thanks for the explanation!

Does this mean that, theoretically, I could just run through all the cached proposed edits and reject everything? Could we track the number of rejections and set a threshold for removing them from the list of proposed edits? (Say, 3 rejections?)

**Comment by VorontsovIE** [comment]
Yes, anybody can reject all the suggestions. I think, it'd be better to include info about a user who rejected an edit into cache - so that it'd be simple to rollback malicious user's contribution.

**Comment by jorlowitz** [comment]
Ilya!

This is so awesome.  Thank you so much for making this feature :) :)

Jake Orlowitz
Head of the Wikipedia Library

**Pull request merged**
