### PR TITLE
Set hdl-access=free when adding a handle identifier

### PR DESCRIPTION
**Pull request by nemobis**
Adds the ability to propose more than one parameter change at a time,
for now only for newly added links.

Bug: T228632

### CODE REVIEW

**Comment by nemobis** [comment]
Didn't test whether the edit actually works, though.

**Comment by wetneb** [comment]
You can try deploying it and see if it works (by checking out your branch on toollabs).

**Comment by nemobis** [comment]
Antonin Delpeuch, 23/07/19 08:41:
> You can try deploying it and see if it works (by checking out your 
> branch on toollabs).

Indeed, that's what I usually do (for better or worse).

**Comment by nemobis** [comment]
Seems to work fine:
https://en.wikipedia.org/w/index.php?title=Multi-label_classification&diff=prev&oldid=907681847

**Pull request merged**
